apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: hub-only
  namespace: openshift-gitops
spec:
  clusterSet: hub-only
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: dev-only
  namespace: openshift-gitops
spec:
  clusterSet: dev-only
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: dev-only
  namespace: shared-gitops
spec:
  clusterSet: dev-only
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: qa-only
  namespace: openshift-gitops
spec:
  clusterSet: qa-only
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: uat-only
  namespace: openshift-gitops
spec:
  clusterSet: uat-only
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: prod-only
  namespace: openshift-gitops
spec:
  clusterSet: prod-only