apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source
spec:
  data: Hello from Ping Source!
  schedule: '* * * * *'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display