apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink-direct
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
        - image: quay.io/openshift-knative/showcase
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink-subscription-a
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
        - image: quay.io/openshift-knative/showcase
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink-subscription-b
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
        - image: quay.io/openshift-knative/showcase
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink-trigger-kafka
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
        - image: quay.io/openshift-knative/showcase
  traffic:
    - latestRevision: true
      percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink-trigger-ping
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
        - image: quay.io/openshift-knative/showcase
  traffic:
    - latestRevision: true
      percent: 100