apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-operators
  namespace: open-cluster-management-global-set
spec:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-gitops-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: openshift-gitops-operator
            channel: latest
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-serverless-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: serverless-operator
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
