apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: example-console
  namespace: kafka-console
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  hostname: '{{ .Values.kafkaconsoleurl }}'
  kafkaClusters:
    - listener: plain
      name: my-cluster
      namespace: kafka
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: kafka-console
spec:
  applicationMenu:
    section: Kafka
    imageURL: 'https://svn.apache.org/repos/asf/kafka/site/logos/originals/png/ICON%20-%20White%20on%20Transparent.png'
  href: 'https://{{ .Values.kafkaconsoleurl }}'
  location: ApplicationMenu
  text: Kafka Console