apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-keda-q9mht
  namespace: openshift-keda
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  upgradeStrategy: Default