apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: my-broker-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 5
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: my-controller-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 5
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim