kind: Namespace
apiVersion: v1
metadata:
  name: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: Namespace
apiVersion: v1
metadata:
  name: kafka-console
  annotations:
    argocd.argoproj.io/sync-wave: "0"