apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-streams
  namespace: kafka
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-streams-console
  namespace: kafka-console
spec:
  upgradeStrategy: Default