apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: kafka
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams-console
  namespace: kafka-console
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: amq-streams-console
  source: redhat-operators
  sourceNamespace: openshift-marketplace