apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rollouts-demo
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
        - image: 'quay.io/openshiftdemos/rollouts-demo:green'
          name: rollouts-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
  traffic:
    - latestRevision: false
      percent: 0
      tag: blue
      revisionName: rollouts-demo-00001
    - latestRevision: true
      percent: 100
      tag: green