###
# Blue-Green/Canary - Initial 'blue' version
###
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: rollouts-demo
# spec:
#   template:
#     spec:
#       containerConcurrency: 1
#       containers:
#         - image: 'quay.io/openshiftdemos/rollouts-demo:blue'
#           name: rollouts-demo
#           ports:
#             - containerPort: 8080
#               protocol: TCP
#           resources:
#             limits:
#               cpu: 200m
#               memory: 512Mi
#             requests:
#               cpu: 100m
#               memory: 256Mi
#   traffic:
#     - latestRevision: true
#       percent: 100
#       tag: blue
#     - latestRevision: true
#       percent: 0
#       tag: green

###
# Blue-Green/Canary - Stage 'green' version for Testing in Production environment
###
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: rollouts-demo
# spec:
#   template:
#     spec:
#       containerConcurrency: 1
#       containers:
#         - image: 'quay.io/openshiftdemos/rollouts-demo:green'
#           name: rollouts-demo
#           ports:
#             - containerPort: 8080
#               protocol: TCP
#           resources:
#             limits:
#               cpu: 200m
#               memory: 512Mi
#             requests:
#               cpu: 100m
#               memory: 256Mi
#   traffic:
#     - revisionName: rollouts-demo-00001
#       percent: 100
#       tag: blue
#     - latestRevision: true
#       percent: 0
#       tag: green

###
# Blue-Green - Promote 'green' version to Production
###
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: rollouts-demo
# spec:
#   template:
#     spec:
#       containerConcurrency: 1
#       containers:
#         - image: 'quay.io/openshiftdemos/rollouts-demo:green'
#           name: rollouts-demo
#           ports:
#             - containerPort: 8080
#               protocol: TCP
#           resources:
#             limits:
#               cpu: 200m
#               memory: 512Mi
#             requests:
#               cpu: 100m
#               memory: 256Mi
#   traffic:
#     - revisionName: rollouts-demo-00001
#       percent: 0
#       tag: blue
#     - latestRevision: true
#       percent: 100
#       tag: green

###
# Canary - Rollout 20% 'green' version to Production
###
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: rollouts-demo
# spec:
#   template:
#     spec:
#       containerConcurrency: 1
#       containers:
#         - image: 'quay.io/openshiftdemos/rollouts-demo:green'
#           name: rollouts-demo
#           ports:
#             - containerPort: 8080
#               protocol: TCP
#           resources:
#             limits:
#               cpu: 200m
#               memory: 512Mi
#             requests:
#               cpu: 100m
#               memory: 256Mi
#   traffic:
#     - revisionName: rollouts-demo-00001
#       percent: 80
#       tag: blue
#     - latestRevision: true
#       percent: 20
#       tag: green

###
# Canary - Rollout 80% 'green' version to Production
###
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: rollouts-demo
# spec:
#   template:
#     spec:
#       containerConcurrency: 1
#       containers:
#         - image: 'quay.io/openshiftdemos/rollouts-demo:green'
#           name: rollouts-demo
#           ports:
#             - containerPort: 8080
#               protocol: TCP
#           resources:
#             limits:
#               cpu: 200m
#               memory: 512Mi
#             requests:
#               cpu: 100m
#               memory: 256Mi
#   traffic:
#     - revisionName: rollouts-demo-00001
#       percent: 20
#       tag: blue
#     - latestRevision: true
#       percent: 80
#       tag: green

###
# Canary - Rollout 100% 'green' version to Production
###
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rollouts-demo
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: 'quay.io/openshiftdemos/rollouts-demo:green'
          name: rollouts-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  traffic:
    - revisionName: rollouts-demo-00001
      percent: 0
      tag: blue
    - latestRevision: true
      percent: 100
      tag: green