apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rollouts-demo
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: 'quay.io/openshiftdemos/rollouts-demo:green'
          name: rollouts-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  traffic:
    - revisionName: rollouts-demo-00001
      percent: 100
      tag: blue
    - latestRevision: true
      percent: 0
      tag: green