kind: Namespace
apiVersion: v1
metadata:
  name: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: Namespace
apiVersion: v1
metadata:
  name: knative-serving
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: Namespace
apiVersion: v1
metadata:
  name: knative-eventing
  annotations:
    argocd.argoproj.io/sync-wave: "0"